services:
  postgres-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passadmin
      POSTGRES_DB: ch
      POSTGRES_USER: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init-pgvector.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: